ln -s riscv32-unknown-elf-addr2line     ri5cy-unknown-elf-addr2line  
ln -s riscv32-unknown-elf-ar            ri5cy-unknown-elf-ar 
ln -s riscv32-unknown-elf-as            ri5cy-unknown-elf-as 
ln -s riscv32-unknown-elf-c++           ri5cy-unknown-elf-c++ 
ln -s riscv32-unknown-elf-c++filt       ri5cy-unknown-elf-c++filt 
ln -s riscv32-unknown-elf-cpp           ri5cy-unknown-elf-cpp  
ln -s riscv32-unknown-elf-elfedit       ri5cy-unknown-elf-elfedit  
ln -s riscv32-unknown-elf-g++           ri5cy-unknown-elf-g++ 
ln -s riscv32-unknown-elf-gcc           ri5cy-unknown-elf-gcc  
ln -s riscv32-unknown-elf-gcc-5.2.0     ri5cy-unknown-elf-gcc-5.2.0 
ln -s riscv32-unknown-elf-gcc-ar        ri5cy-unknown-elf-gcc-ar 
ln -s riscv32-unknown-elf-gcc-nm        ri5cy-unknown-elf-gcc-nm 
ln -s riscv32-unknown-elf-gcc-ranlib    ri5cy-unknown-elf-gcc-ranlib 
ln -s riscv32-unknown-elf-gcov          ri5cy-unknown-elf-gcov  
ln -s riscv32-unknown-elf-gcov-tool     ri5cy-unknown-elf-gcov-tool 
ln -s riscv32-unknown-elf-gprof         ri5cy-unknown-elf-gprof  
ln -s riscv32-unknown-elf-ld            ri5cy-unknown-elf-ld  
ln -s riscv32-unknown-elf-ld.bfd        ri5cy-unknown-elf-ld.bfd 
ln -s riscv32-unknown-elf-nm            ri5cy-unknown-elf-nm  
ln -s riscv32-unknown-elf-objcopy       ri5cy-unknown-elf-objcopy  
ln -s riscv32-unknown-elf-objdump       ri5cy-unknown-elf-objdump  
ln -s riscv32-unknown-elf-ranlib        ri5cy-unknown-elf-ranlib  
ln -s riscv32-unknown-elf-readelf       ri5cy-unknown-elf-readelf  
ln -s riscv32-unknown-elf-size          ri5cy-unknown-elf-size  
ln -s riscv32-unknown-elf-strings       ri5cy-unknown-elf-strings  
ln -s riscv32-unknown-elf-strip         ri5cy-unknown-elf-strip  