ln -s riscv32-unknown-elf-addr2line    klessydra-tiny-unknown-elf-addr2line
ln -s riscv32-unknown-elf-ar           klessydra-tiny-unknown-elf-ar
ln -s riscv32-unknown-elf-as           klessydra-tiny-unknown-elf-as
ln -s riscv32-unknown-elf-c++          klessydra-tiny-unknown-elf-c++
ln -s riscv32-unknown-elf-c++filt      klessydra-tiny-unknown-elf-c++filt
ln -s riscv32-unknown-elf-cpp          klessydra-tiny-unknown-elf-cpp
ln -s riscv32-unknown-elf-elfedit      klessydra-tiny-unknown-elf-elfedit
ln -s riscv32-unknown-elf-g++          klessydra-tiny-unknown-elf-g++
ln -s riscv32-unknown-elf-gcc          klessydra-tiny-unknown-elf-gcc
ln -s riscv32-unknown-elf-gcc-8.2.0    klessydra-tiny-unknown-elf-gcc-8.2.0
ln -s riscv32-unknown-elf-gcc-ar       klessydra-tiny-unknown-elf-gcc-ar
ln -s riscv32-unknown-elf-gcc-nm       klessydra-tiny-unknown-elf-gcc-nm
ln -s riscv32-unknown-elf-gcc-ranlib   klessydra-tiny-unknown-elf-gcc-ranlib
ln -s riscv32-unknown-elf-gcov         klessydra-tiny-unknown-elf-gcov
ln -s riscv32-unknown-elf-gcov-dump    klessydra-tiny-unknown-elf-gcov-dump
ln -s riscv32-unknown-elf-gcov-tool    klessydra-tiny-unknown-elf-gcov-tool
ln -s riscv32-unknown-elf-gdb          klessydra-tiny-unknown-elf-gdb
ln -s riscv32-unknown-elf-gprof        klessydra-tiny-unknown-elf-gprof
ln -s riscv32-unknown-elf-ld           klessydra-tiny-unknown-elf-ld
ln -s riscv32-unknown-elf-ld.bfd       klessydra-tiny-unknown-elf-ld.bfd
ln -s riscv32-unknown-elf-nm           klessydra-tiny-unknown-elf-nm
ln -s riscv32-unknown-elf-objcopy      klessydra-tiny-unknown-elf-objcopy
ln -s riscv32-unknown-elf-objdump      klessydra-tiny-unknown-elf-objdump
ln -s riscv32-unknown-elf-ranlib       klessydra-tiny-unknown-elf-ranlib
ln -s riscv32-unknown-elf-readelf      klessydra-tiny-unknown-elf-readelf
ln -s riscv32-unknown-elf-run          klessydra-tiny-unknown-elf-run
ln -s riscv32-unknown-elf-size         klessydra-tiny-unknown-elf-size
ln -s riscv32-unknown-elf-strings      klessydra-tiny-unknown-elf-strings
ln -s riscv32-unknown-elf-strip        klessydra-tiny-unknown-elf-strip
